version: '2.2'
services:
  my_elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  nginx:
    image: nginx
    volumes:
      - ./configuration:/etc/nginx
    ports:
      - 8080:8080
    environment:
      - NGINX_PORT=8080