version: '3.5'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms128mb -Xmx128mb"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

#  nginx:
#    image: nginx
#    volumes:
#      - ./configuration:/etc/nginx
#    ports:
#      - 80:80
#    environment:
#      - NGINX_PORT=80
