version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9201:9200
    networks:
      - nginx-elastic
  nginx:
    image: nginx
    volumes:
      - ./configuration:/etc/nginx
    ports:
      - "9200:80"
    environment:
      - NGINX_PORT=80
    networks:
      - nginx-elastic

networks:
  nginx-elastic:
    driver: bridge
